title: BIGX
description: "个人经历与比赛复现记录"
url: "https://bigx-bigx.github.io"
baseurl: ""
lang: zh-CN
timezone: Asia/Shanghai
future: true
page_excerpts: true

author:
  name: BIGX
  github: "https://github.com/BIGX-bigx"
  avatar: "https://github.com/BIGX-bigx.png"

permalink: /:categories/:title/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: BIGX
  - scope:
      path: "articles"
      type: pages
    values:
      layout: post
      author: BIGX

markdown: kramdown
kramdown:
  input: GFM

optional_front_matter:
  remove_originals: true

titles_from_headings:
  enabled: true
  strip_title: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
